spring.application.name=simposium

# URL de conexión usando las variables del .env
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=username
spring.datasource.password=password

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}
spring.jpa.show-sql=${DB_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect